-- | Typed statecharts generated from SCXML.
--
-- @
-- [scxml|
-- <scxml initial="Closed">
--   <state id="Closed">
--     <onentry><script>lockBolt</script></onentry>
--     <transition event="Open" target="Opened"/>
--   </state>
--   <state id="Opened"><transition event="Close" target="Closed"/></state>
-- </scxml>
-- |]
--
-- initiateStateMachine :: MonadIO m => m FsmState
-- notifyStateMachine   :: MonadIO m => FsmState -> FsmEvent -> m FsmState
--
-- lockBolt :: MonadIO m => FsmState -> Maybe FsmEvent -> m (Maybe FsmEvent)
-- lockBolt _ _ = liftIO (putStrLn "clunk") >> pure Nothing
-- @
--
-- The quasiquote generates @FsmState@, @FsmEvent@ and the functions
-- @initiateStateMachine@ and @notifyStateMachine@, which call the callbacks
-- named in @<script>@ elements. State ids and event names are used verbatim as
-- constructor names, so the generated names are fixed and a module holds one
-- chart. Callbacks are defined in the same module, after the quasiquote, and
-- must all live in the same monad, which the type checker enforces.
--
-- Signatures for the two generated functions are optional. They are inferred
-- when the callbacks are in a concrete monad; when the callbacks are
-- polymorphic, @initiateStateMachine@ takes no arguments and so needs either
-- a signature or @NoMonomorphismRestriction@.
--
-- Two more functions are generated for storing a state outside Haskell:
--
-- @
-- serializeStateMachine   :: FsmState -> [Text]
-- deserializeStateMachine :: [Text] -> Maybe FsmState
-- @
--
-- This module exports only the quasiquoter. Everything a chart needs is
-- generated into your own module, so there is nothing else to import.
module Statechart (scxml) where

import Statechart.TH (scxml)
